# Generated by Django 4.1 on 2022-09-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees", name="address", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="employees",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employees",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="employees", name="phone", field=models.IntegerField(null=True),
        ),
    ]
